# Generated by Django 2.2 on 2019-04-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190413_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Board',
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='manager.Board'),
            preserve_default=False,
        ),
    ]
